import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createApp } from '../server.mjs';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = fileURLToPath(new URL('..', import.meta.url));
const directory = await mkdtemp(join(tmpdir(), 'mesh-browser-'));
const { server, access } = createApp({ directory, detect: async () => ({ codex: { installed: true, signedIn: true }, claude: { installed: true, signedIn: true } }) });
let browser;
try {
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '0.0.0.0', resolve); });
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const base = `http://127.0.0.1:${server.address().port}`;
  await page.goto(base); await page.waitForSelector('.participant');
  assert.equal(await page.locator('.participant').count(), 2);
  assert.equal(await page.locator('#call-estimate').textContent(), 'About 8 calls, up to 12');
  await mkdir(join(root, 'artifacts'), { recursive: true });
  await page.screenshot({ path: join(root, 'artifacts', 'desktop.png'), fullPage: true });
  await page.click('#start'); assert.match(await page.locator('#toast').textContent(), /Describe/);
  await page.click('#connections-nav'); await page.click('#add-connection');
  await page.selectOption('#provider-type', 'compatible');
  await page.fill('#provider-name', 'Test <img src=x onerror=alert(1)>');
  await page.fill('#provider-model', 'test-model'); await page.fill('#provider-url', 'http://localhost:11434/v1');
  await page.fill('#provider-key', 'browser-test-key'); await page.fill('#provider-role', 'Test reviewer');
  await page.click('#provider-form button[type=submit]'); await page.waitForSelector('#provider-dialog', { state: 'hidden' });
  assert.equal(await page.locator('.connection-card').count(), 3);
  assert.equal(await page.locator('.connection-card img').count(), 0);
  const connection = await page.locator('.connection-card').last(); await connection.locator('[data-edit]').click();
  assert.equal(await page.inputValue('#provider-key'), ''); await page.click('#delete-connection');
  await page.waitForSelector('#provider-dialog', { state: 'hidden' });
  await page.click('#workspace-nav'); await page.click('#demo');
  await page.waitForFunction(() => document.querySelector('#run-title').textContent === 'The council reached consensus.');
  assert.equal(await page.locator('.msg').count(), 8);
  await page.click('[data-tab=answer]'); assert.match(await page.locator('#answer').textContent(), /scripted demonstration/);
  const exportHref = await page.locator('#export').getAttribute('href');
  const transcript = await (await page.request.get(base + exportHref)).text(); assert.match(transcript, /Demo reviewer/);
  await page.screenshot({ path: join(root, 'artifacts', 'discussion.png'), fullPage: true });
  await page.reload(); await page.waitForSelector('.history-item'); await page.locator('.history-item').first().click();
  await page.waitForFunction(() => document.querySelector('#run-title').textContent === 'The council reached consensus.');
  await page.click('#new-discussion'); await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(root, 'artifacts', 'mobile.png'), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile has horizontal overflow');
  await page.click('#demo'); await page.waitForSelector('#cancel:not(.hidden)'); await page.click('#cancel');
  await page.waitForFunction(() => document.querySelector('#run-title').textContent === 'Meeting cancelled.');
  if (!access.addresses.length) throw new Error('A LAN interface is required for the LAN browser check.');
  const lanContext = await browser.newContext();
  const lan = await lanContext.newPage();
  await lan.goto(`http://${access.addresses[0]}:${server.address().port}`);
  await lan.waitForSelector('#pair-code');
  await lan.screenshot({ path: join(root, 'artifacts', 'lan-pairing.png'), fullPage: true });
  assert.equal((await lan.request.get(`http://${access.addresses[0]}:${server.address().port}/api/bootstrap`)).status(), 401);
  await lan.fill('#pair-code', 'wrong'); await lan.click('#pair-form button');
  await lan.waitForFunction(() => document.querySelector('#pair-error').textContent.includes('incorrect'));
  await lan.fill('#pair-code', access.code); await lan.click('#pair-form button');
  await lan.waitForSelector('.participant');
  assert.equal(await lan.locator('#session-label').textContent(), 'Paired LAN session');
  assert.ok(await lan.locator('#lan-button').isHidden());
  await lanContext.close();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: desktop, mobile, connections, escaped content, demo, history, export, cancellation, and LAN pairing.');
} finally {
  await browser?.close();
  server.closeAllConnections(); await new Promise(resolve => server.close(resolve));
  await rm(directory, { recursive: true, force: true });
}
